export const REQUEST_LOCATION_INFO = "REQUEST_LOCATION_INFO";
export const SUCCESS_LOCATION_INFO = "SUCCESS_LOCATION_INFO";
export const FAIL_LOCATION_INFO = "FAIL_LOCATION_INFO";
export const CLEAR  = "CLEAR";